spring.application.name=examenProgramariMpai

# Setam portul pentru a putea accesa aplica?ia la localhost:8080
server.port=8080
spring.h2.console.enabled=true
# Configurare H2 Database (In-Memory)
spring.datasource.url=jdbc:h2:mem:programariDB
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Crearea automat? a tabelelor din entit??i la pornire
spring.jpa.hibernate.ddl-auto=create-drop
